version: '3.4'

services:
  cultsimhelpguide:
    image: cultsimhelpguide
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
