version: '3.4'

services:
  cultsimhelpguide:
    image: cultsimhelpguide:4.7.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
  cultsimhelpguide-latest:
    image: cultsimhelpguide
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:80
      